--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/AntiAltAccounts
build-by-default: true
branches:
- main
projects:
  AntiAltAccounts:
    path: ""
    libs:
      - src: ACM-PocketMine-MP/DiscordWebhookAPI/DiscordWebhookAPI
        version: ^1.0.3
      - src: DaPigGuy/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^1.0.0
    lint: false
...
