--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/AntiAltAccounts
build-by-default: true
branches:
- main
projects:
  AntiAltAccounts:
    path: ""
    libs:
      - src: FernanACM/DiscordWebhookAPI/DiscordWebhookAPI
        version: ^1.0.3
...
